name: iOS CI

on:
  pull_request:
    branches: [ develop, main ]
  push:
    branches: [ develop ]

jobs:
  build-test:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Check SwiftLint version
        run: swiftlint version

      - name: Update SwiftLint (if needed)
        run: brew upgrade swiftlint || brew reinstall swiftlint

      - name: Run SwiftLint (Using JSON Reporter for Better Logs)
        run: swiftlint --reporter json | jq .

      - name: Install Looper (if available)
        run: |
          if brew info looper &>/dev/null; then
            brew install looper
          else
            echo "Looper not found in Homebrew, trying to tap..."
            brew tap looper/tap || true
            brew install looper || true
          fi

      - name: Run Unit Tests
        run: |
          xcodebuild test \
          -scheme AuthenticationLibrary \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          -enableCodeCoverage YES | xcpretty && exit ${PIPESTATUS[0]}

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/reports
